name: Check and test Python package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
          python-version:
            - "3.7"
            - "3.8"
            - "3.9"
            - "3.10"
            - "3.11"
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check with black
        run: poetry run black --check --diff autohooks
      - name: Check with flake8
        run: poetry run flake8 autohooks

  type-checking:
    name: Type-checker
    strategy:
        matrix:
          python-version:
            - "3.7"
            - "3.8"
            - "3.9"
            - "3.10"
            - "3.11"
    uses: greenbone/workflows/.github/workflows/typing-python.yml@main
    with:
      python-version: ${{ matrix.python-version }}

  test:
    name: Run all tests
    strategy:
        matrix:
          python-version:
            - "3.7"
            - "3.8"
            - "3.9"
            - "3.10"
            - "3.11"
    uses: greenbone/workflows/.github/workflows/test-python.yml@main
    with:
      python-version: ${{ matrix.python-version }}

  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v3
        with:
          python-version: "3.10"
          token: ${{ secrets.CODECOV_TOKEN }}

  check-version:
    name: Check versioning for consistency
    uses: greenbone/workflows/.github/workflows/check-version.yml@main
