name: Release Python package with pontos

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Create a new release with pontos
    # If the event is a workflow_dispatch or the label 'make release' is set and PR is closed because of a merge
    if: (github.event_name == 'workflow_dispatch') || (contains( github.event.pull_request.labels.*.name, 'make release') && github.event.pull_request.merged == true)
    runs-on: "ubuntu-latest"
    steps:
      - name: Setting the Reference
        id: ref
        run: |
          if [[ "${{ github.event_name }}" = "workflow_dispatch" ]]; then
            echo "release_ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "release_ref=${{ github.base_ref }}" >> $GITHUB_OUTPUT
          fi
      - name: Release with release action
        uses: greenbone/actions/release@v2
        with:
          github-user: ${{ secrets.GREENBONE_BOT }}
          github-user-mail: ${{ secrets.GREENBONE_BOT_MAIL }}
          github-user-token: ${{ secrets.GREENBONE_BOT_TOKEN }}
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          release-type: calendar
          ref: ${{ steps.ref.outputs.release_ref }}
